version: "3.9"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins 
    env_file:
      - .env 
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - JAVA_OPTS=-Djenkins.httpListenAddress=0.0.0.0
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jcasc:/var/jenkins_home/casc_configs:ro
    depends_on:
      - dind

  dind:
    image: docker:27-dind
    container_name: jenkins-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    ports:
      - "2375:2375"
    extra_hosts:
      - "harbor.local:192.168.0.250"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - dind_storage:/var/lib/docker
      - ./daemon.json:/etc/docker/daemon.json:ro

  iac-agent:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    container_name: jenkins-iac-agent
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - JENKINS_URL=http://192.168.0.250:8080
      - JENKINS_AGENT_NAME=iac-agent
      - JENKINS_SECRET=db67e9e9a8c74079e35e34a033d9c1e011669cb8279150b53bb43f7306156005
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - ~/.ssh:/home/jenkins/.ssh
  
  postgres:
    image: postgres:15
    container_name: sonar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    ports:
      - "55432:5432"   # Puerto personalizado en el host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sonar:
    image: sonarqube:latest
    container_name: sonar
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

volumes:
  jenkins_home:
  dind_storage:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  postgres_data:
